In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(6, 4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a[1, 2]

6

In [5]:
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [6]:
# Fancy Indexing
a[:, [0, 2, 3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [7]:
a = np.random.randint(1, 100, 24).reshape(6, 4)
a

array([[85, 71, 14, 50],
       [20, 75, 83, 32],
       [88, 17,  5, 85],
       [ 1, 98, 10, 83],
       [92, 21, 90, 17],
       [11, 14, 44, 90]])

In [8]:
a[a > 50]

array([85, 71, 75, 83, 88, 85, 98, 83, 92, 90, 90])

In [9]:
a[a % 2 == 0]

array([14, 50, 20, 32, 88, 98, 10, 92, 90, 14, 44, 90])

In [10]:
a[(a > 50) & (a % 2 == 0)]

array([88, 98, 92, 90, 90])

In [11]:
a[~(a % 7 == 0)]

array([85, 71, 50, 20, 75, 83, 32, 88, 17,  5, 85,  1, 10, 83, 92, 90, 17,
       11, 44, 90])

### Broadcasting

In [13]:
# same shape
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

array([[ 6,  8, 10],
       [12, 14, 16]])

In [14]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
a + b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [17]:
# diff shape
a = np.arange(6).reshape(2, 3)
b = np.arange(3).reshape(1, 3)

In [19]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b

array([[0, 1, 2]])

In [21]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])