In [1]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [8]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(16).reshape(2, 2, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random((3, 4))

array([[0.59166925, 0.91789337, 0.24607116, 0.53306275],
       [0.09444424, 0.84345454, 0.55667673, 0.63293361],
       [0.42121297, 0.66998756, 0.67590453, 0.28231229]])

In [13]:
np.linspace(-10, 10, 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [17]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)


a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
a3.ndim

3

In [19]:
a3.shape

(2, 2, 2)

In [20]:
a2.size

12

In [21]:
a3.itemsize

4

In [22]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [23]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

In [25]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [27]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [28]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
a1 = np.array([1, 2, 3])

In [30]:
a1

array([1, 2, 3])

In [31]:
np.prod(a1, axis=0)

6

In [34]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [35]:
np.sin(a1)

array([0.84147098, 0.90929743, 0.14112001])

In [33]:
np.ceil(np.random.random((2, 3)) * 100)

array([[43., 14., 83.],
       [ 6., 48., 61.]])

### Indexing and Slicing

In [36]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a2[1, 0]

4

In [41]:
a3[1, 0, 1]

5

In [42]:
a3[1, 1, 0]

6

In [43]:
a1[2:5:2]

array([2, 4])

In [44]:
a2[0:2, 1::2]

array([[1, 3],
       [5, 7]])

In [45]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [46]:
a2[1, ::3]

array([4, 7])

In [47]:
a2[0, :]

array([0, 1, 2, 3])

In [49]:
a2[:, 2]

array([ 2,  6, 10])

In [50]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [48]:
a2[1, 0]

4

In [51]:
a3 = np.arange(27).reshape(3, 3, 3)

In [52]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [53]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [54]:
a3[0,1,:]

array([3, 4, 5])