In [1]:
import numpy as np

In [4]:
a = np.random.randint(1, 100, 15)
a

array([27, 97, 27, 96, 17, 80, 39, 54, 61,  6,  2, 13, 64,  1, 36])

In [5]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[68, 49, 10, 70],
       [65, 77, 35, 85],
       [40, 17, 16, 70],
       [76, 62,  2, 82],
       [89, 66, 25, 87],
       [50, 43,  2, 12]])

In [6]:
np.sort(a)[::-1]

array([97, 96, 80, 64, 61, 54, 39, 36, 27, 27, 17, 13,  6,  2,  1])

In [7]:
np.sort(b, axis=0)

array([[40, 17,  2, 12],
       [50, 43,  2, 70],
       [65, 49, 10, 70],
       [68, 62, 16, 82],
       [76, 66, 25, 85],
       [89, 77, 35, 87]])

In [8]:
np.append(a, 200)

array([ 27,  97,  27,  96,  17,  80,  39,  54,  61,   6,   2,  13,  64,
         1,  36, 200])

In [9]:
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[6.80000000e+01, 4.90000000e+01, 1.00000000e+01, 7.00000000e+01,
        3.97094473e-03],
       [6.50000000e+01, 7.70000000e+01, 3.50000000e+01, 8.50000000e+01,
        8.57568201e-01],
       [4.00000000e+01, 1.70000000e+01, 1.60000000e+01, 7.00000000e+01,
        5.94653323e-01],
       [7.60000000e+01, 6.20000000e+01, 2.00000000e+00, 8.20000000e+01,
        5.59763763e-01],
       [8.90000000e+01, 6.60000000e+01, 2.50000000e+01, 8.70000000e+01,
        9.75099240e-01],
       [5.00000000e+01, 4.30000000e+01, 2.00000000e+00, 1.20000000e+01,
        1.03596882e-01]])

### concatenate

In [10]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

In [11]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [13]:
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [17]:
a.shape

(15,)

In [15]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [16]:
np.expand_dims(a, axis=1)

array([[27],
       [97],
       [27],
       [96],
       [17],
       [80],
       [39],
       [54],
       [61],
       [ 6],
       [ 2],
       [13],
       [64],
       [ 1],
       [36]])

In [18]:
a

array([27, 97, 27, 96, 17, 80, 39, 54, 61,  6,  2, 13, 64,  1, 36])

In [19]:
np.where(a > 50)

(array([ 1,  3,  5,  7,  8, 12], dtype=int64),)

In [20]:
np.where(a > 50, 0, a)

array([27,  0, 27,  0, 17,  0, 39,  0,  0,  6,  2, 13,  0,  1, 36])

In [21]:
np.where(a % 2 == 0, 0, a)

array([27, 97, 27,  0, 17,  0, 39,  0, 61,  0,  0, 13,  0,  1,  0])

In [24]:
np.percentile(a, 50)

36.0

In [25]:
np.median(a)

36.0

In [26]:
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

a[np.isin(a, items)]

array([80])

In [27]:
np.delete(a, [0, 2, 4])

array([97, 96, 80, 39, 54, 61,  6,  2, 13, 64,  1, 36])

In [28]:
a

array([27, 97, 27, 96, 17, 80, 39, 54, 61,  6,  2, 13, 64,  1, 36])

In [29]:
np.flip(a)

array([36,  1, 64, 13,  2,  6, 61, 54, 39, 80, 17, 96, 27, 97, 27])

In [30]:
b

array([[68, 49, 10, 70],
       [65, 77, 35, 85],
       [40, 17, 16, 70],
       [76, 62,  2, 82],
       [89, 66, 25, 87],
       [50, 43,  2, 12]])

In [31]:
np.flip(b,axis=1)

array([[70, 10, 49, 68],
       [85, 35, 77, 65],
       [70, 16, 17, 40],
       [82,  2, 62, 76],
       [87, 25, 66, 89],
       [12,  2, 43, 50]])